name: CI/CD Pipeline

on:
    push:
        branches:
            - master # Change to your default branch

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "22.x" # Specify your Node.js version

            - name: Install dependencies
              run: npm install

            - name: Build application
              run: npm run build # This command builds your Next.js app

            - name: Deploy to VPS
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # Add your SSH key as a secret in GitHub
                  VPS_IP: ${{ secrets.VPS_IP }} # Add your VPS IP as a secret in GitHub
                  VPS_USER: ${{ secrets.VPS_USER }} # Add your VPS user as a secret in GitHub
              run: |
                  echo "$SSH_PRIVATE_KEY" > private_key
                  chmod 600 private_key
                  scp -o StrictHostKeyChecking=no -i private_key -r .next/* $VPS_USER@$VPS_IP:code/frontend/.next
                  scp -o StrictHostKeyChecking=no -i private_key -r package.json $VPS_USER@$VPS_IP:code/frontend
                  scp -o StrictHostKeyChecking=no -i private_key -r package-lock.json $VPS_USER@$VPS_IP:code/frontend
                  ssh -o StrictHostKeyChecking=no -i private_key $VPS_USER@$VPS_IP "cd code/frontend && npm install --production && pm2 restart frontend"
